-- AlterEnum
ALTER TYPE "AuthAuditEventType" ADD VALUE 'LOGOUT_ALL';
ALTER TYPE "AuthAuditEventType" ADD VALUE 'SESSION_REVOKED_BY_USER';
ALTER TYPE "AuthAuditEventType" ADD VALUE 'SESSION_REVOKED_ADMIN';
